### ISSUE TITLE
Server offline? 

### ISSUE THREAD

**Issue by iTzJoBu** [montlikadani/TeleportSigns#10]
The sign shows me the server is offline, but its online at /server... 
bungee config: 
```
forge_support: false
connection_throttle_limit: 3
timeout: 30000
online_mode: true
log_commands: false
listeners:
- query_port: 25565
  motd: '&9          NoFilterJustSmog&7.&bxyz                                          &f>&3
    by&b Max&3 und&b Joshua'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1000
  tab_size: 60
  force_default_server: false
connection_throttle: 4000
groups:
  md_5:
  - admin
  De4thPlayZ:
  - admin
  iTz_JoBu:
  - admin
log_pings: true
ip_forward: false
prevent_proxy_connections: false
network_compression_threshold: 256
disabled_commands:
- disabledcommandhere
stats: 78a39668-3201-44df-887a-86a53ad8b16b
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25566
    restricted: false
  skygames:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25567
    restricted: false
  citybuild:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25568
    restricted: false
player_limit: -1
```

tsigns config:
```
#-----------------------------OOO-----------------------------------#
#                TeleportSigns Configuration File                   #
#-----------------------------OOO-----------------------------------#
# config.yml file. Plugin version: 2.2.1                            #
# Author, created by: montlikadani                                  #
#-----------------------------OOO-----------------------------------#
# [Default configuration]                                           #
# github.com/montlikadani/TeleportSigns/blob/master/config.yml      #
#                                                                   #
# [Placeholders]                                                    #
# https://github.com/montlikadani/TeleportSigns/wiki/Placeholders   #
#                                                                   #
# [Tips]                                                            #
# - Use color coding '&' character, on this page:                   #
# http://minecraft.gamepedia.com/Formatting_codes                   #
# - If you find a bug, send here:                                   #
# https://github.com/montlikadani/TeleportSigns/issues              #
# - If the string is empty does not send the message.               #
#-----------------------------OOO-----------------------------------#

# Options
options:
  # Log plugin messages into console.
  logconsole: true

  # Sign usage time.
  # This ignoring with this permission: teleportsigns.use.nocooldown
  use-cooldown: 5

  # Sign updates in ticks. 20 ticks = 1 second.
  sign-updates: 200

  # How much time do you start the server pinging? (In seconds)
  ping-interval: 30
  # Important! If you do not want the pinging to end ping-timeout to be smaller than one and
  # take the ping interval by one more.
  # How much time does the server pinging down? (In seconds)
  ping-timeout: 29

  # Ignoring the player sneaking when clicking on the sign.
  ignore-player-sneaking: true

  # Defines a background of the sign.
  background:
    enable: false
    # Possible types: glass, wool, clay
    type: glass

# The servers that players join.
servers:
  lobby:
    # Server IP address and port.
    address: "5.189.131.232:25566"
    # Display name that are on the sign.
    displayname: "lobby"
  skygames:
    # Server IP address and port.
    address: "5.189.131.232:25567"
    # Display name that are on the sign.
    displayname: "skygames"
  citybuild:
    # Server IP address and port.
    address: "5.189.131.232:25568"
    # Display name that are on the sign.
    displayname: "citybuild"
    

#=========================================#
#             Plugin Settings             #
#=========================================#
# The TeleportSigns plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %prefix%, %newline% placeholder.
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v2.2.1&a!'
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# DO NOT CHANGE THIS!
config-version: 4
```

MC 1.14.3
Spigot

Thank you for help
