### ISSUE TITLE
I can't use the sign because Server offline but the Server is online.

### ISSUE THREAD

**Issue by Twisterels** [montlikadani/TeleportSigns#11]
Hello I need help,
I can't use the sign because Server offline but the Server is online.

![Fehler](https://user-images.githubusercontent.com/25160240/60913314-67f67300-a287-11e9-9343-002ffbb2216f.PNG)

Bungeecord config:
```
forge_support: false
connection_throttle_limit: 3
timeout: 30000
online_mode: true
log_commands: false
listeners:
- query_port: 25577
  motd: '&eInfected &5Gilden &6Server.'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 128.0.120.232:25577
  max_players: 1
  tab_size: 60
  force_default_server: true
connection_throttle: -1
groups:
  Mark_Dominik:
  - admin
  jdoggette:
  - mod
  darkels110:
  - srmod
  VelvetCroweZ:
  - mod
log_pings: true
ip_forward: false
prevent_proxy_connections: false
network_compression_threshold: 256
disabled_commands:
- disabledcommandhere
stats: 879462d6-b0f9-452e-92b7-9bc223259649
permissions:
  default: null
  mod:
  - bungeecord.command.alert
  - ab.ban.perma
  - ab.ban.notify
  - ab.kick.use
  - ab.kick.notify
  - ab.mute.perma
  - ab.mute.temp
  - ab.mute.notify
  - ab.mute.undo
  - tc.see
  srmod:
  - bungeecord.command.alert
  - bungeecord.command.server
  - ab.ban.perma
  - ab.ban.notify
  - ab.kick.use
  - ab.kick.notify
  - ab.mute.perma
  - ab.mute.temp
  - ab.mute.notify
  - ab.mute.undo
  - tc.see
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.server
  - bungeecord.command.list
  - ab.ban.perma
  - ab.ban.notify
  - ab.ban.exempt
  - ab.ban.undo
  - ab.ipban.perma
  - ab.ipban.temp
  - ab.ipban.exempt
  - ab.ipban.notify
  - ab.kick.use
  - ab.kick.notify
  - ab.kick.exempt
  - ab.mute.perma
  - ab.mute.temp
  - ab.mute.notify
  - ab.mute.undo
  - ab.mute.exempt
  - tc.see
servers:
  lobby:
    motd: '&eInfected &5Gilden &6Server.'
    address: 128.0.120.232:25565
    restricted: false
  mcserver:
    motd: '&aSurvival &6Server'
    address: 128.0.120.232:25585
    restricted: false
  ffa:
    motd: '&5FFA &eServer'
    address: 128.0.120.232:25515
    restricted: false
  Testserver:
    motd: '&eTestserver'
    address: 128.0.120.232:25500
    restricted: false
  Superjump1:
    motd: '&eTestserver'
    address: 128.0.120.232:25525
    restricted: false
  Superjump2:
    motd: '&eTestserver'
    address: 128.0.120.232:25535
    restricted: false
  Superjump3:
    motd: '&eTestserver'
    address: 128.0.120.232:25545
    restricted: false
player_limit: 30
```
TeleportSigns config:
```
  # Defines a background of the sign.
  background:
    enable: true
    # Possible types: glass, wool, clay
    type: wool

# The servers that players join.
servers:
  lobby:
    # Server IP address and port.
    address: "128.0.120.232:25565"
    # Display name that are on the sign.
    displayname: "lobby"
  mcserver:
    # Server IP address and port.
    address: "128.0.120.232:25585"
    # Display name that are on the sign.
    displayname: "mcserver"
  ffa:
    # Server IP address and port.
    address: "128.0.120.232:25515"
    # Display name that are on the sign.
    displayname: "ffa"
  Testserver:
    # Server IP address and port.
    address: "128.0.120.232:25500"
    # Display name that are on the sign.
    displayname: "Testserver"
  Superjump1:
    # Server IP address and port.
    address: "128.0.120.232:25525"
    # Display name that are on the sign.
    displayname: "Superjump1"
  Superjump2:
    # Server IP address and port.
    address: "128.0.120.232:25535"
    # Display name that are on the sign.
    displayname: "Superjump2"
  Superjump3:
    # Server IP address and port.
    address: "128.0.120.232:25545"
    # Display name that are on the sign.
    displayname: "Superjump3"
#=========================================#
#             Plugin Settings             #
#=========================================#
# The TeleportSigns plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %prefix%, %newline% placeholder.
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v2.2.1&a!'
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# DO NOT CHANGE THIS!
config-version: 4
```

Spigot Version 1.14.2
I hope you can help me.
Thanks!
