### ISSUE TITLE
Error Fetching Data From Server

### ISSUE THREAD

**Issue by MstrTaffy** [montlikadani/TeleportSigns#15]
### Describe your problem to what is
Updated to v2.3.1 to try and get it to see my new 1.15.1 server.

Doesn't see any servers now.

### Details
Plugin version: 2.3.1
Software (Spigot/Bukkit etc.. `/version`) version: Paper 1.13.2 -636

### Console error
```
[21:00:11 WARN]: [TeleportSigns] Error fetching data from server '192.168.0.200:25571'
[21:00:11 WARN]: [TeleportSigns] Error fetching data from server '192.168.0.201:25572'
[21:00:11 WARN]: [TeleportSigns] Error fetching data from server '192.168.0.201:25570'

```

### Configuration file(s)
Send the configuration file(s).
```
#-----------------------------OOO-----------------------------------#
#                TeleportSigns Configuration File                   #
#                Author, created by: montlikadani                   #
#-----------------------------OOO-----------------------------------#
# [Default configuration]                                           #
# github.com/montlikadani/TeleportSigns/blob/master/config.yml      #
#                                                                   #
# [Tips]                                                            #
# - If you find a bug, send here:                                   #
# https://github.com/montlikadani/TeleportSigns/issues              #
#-----------------------------OOO-----------------------------------#

# Options
options:
  # Use external server as a hosted server?
  # If false then using internal server.
  external-server: false

  # Log plugin messages into console.
  logconsole: true

  # Sign usage time to prevent twice connect to that server.
  # This will be ignored with this permission: teleportsigns.use.nocooldown
  use-cooldown: 5

  # Sign updates time in ticks.
  # Example: 20 ticks = 1 second
  sign-updates: 20

  # How much time start the server pinging? (In seconds)
  ping-interval: 30

  # Important! If you do not want the pinging to end ping-timeout to be smaller than one and
  # take the ping interval by one more.
  # How much time does the server pinging down? (In seconds)
  ping-timeout: 29

  # Ignoring the player sneaking when clicking on the sign.
  ignore-player-sneaking: true

  # Defines a background of the sign.
  background:
    enable: true

    # Possible types: glass, wool, clay
    type: glass

# The servers that players join.
servers:
  Stream:
    # Server IP address and port.
    address: "192.168.0.200:25569"
    # Display name that are on the sign.
    displayname: "&n&l&5Stream"
  
  Vanilla:
    # Server IP address and port.
    address: "192.168.0.200:25571"
    # Display name that are on the sign.
    displayname: "&n&l&5Vanilla"
  
  Rev:
    # Server IP address and port.
    address: "192.168.0.201:25570"
    # Display name that are on the sign.
    displayname: "&n&l&5Revelations"
  
  Heroes:
    # Server IP address and port.
    address: "192.168.0.201:25572"
    # Display name that are on the sign.
    displayname: "&n&l&5Heroes"

#=========================================#
#             Plugin Settings             #
#=========================================#
# Check for updates.
check-update: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %newline% placeholder.
plugin-enable: '&6[&2Teleport&eSigns&6]&7 >&a The plugin successfully enabled&6 v2.3.1&a!'
plugin-disable: '&6[&2Teleport&eSigns&6]&7 >&c The plugin successfully disabled!'

# DO NOT CHANGE THIS!
config-version: 5

```

### Screenshots (optional)
Send a few pictures about the problem if you can.
